FROM ghcr.io/washu-it-ris/novnc:ubuntu22.04

RUN apt-get update && /
     apt-get -y install sudo

RUN apt-get clean

RUN adduser --disabled-password --gecos '' docker
RUN adduser docker sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER docker
CMD /bin/bash
